apiVersion: garden.io/v2
kind: Project
name: better-auth-basic-example
defaultEnvironment: local

# This example demonstrates a basic Better Auth setup with:
# - Go-based authentication server
# - Multi-language application servers (TypeScript, Ruby, Rust, Python)

environments:
  - name: local
    defaultNamespace: ${project.name}-dev

providers:
  - name: local-kubernetes
    setupIngressController: nginx
    defaultHostname: better-auth.local
    environments: [local]
    namespace:
      name: ${project.name}-dev
      
    # Garden will auto-detect Docker Desktop, Minikube, k3s, etc.
    # No need to specify context for local development

    # Use local Docker daemon for building images
    buildMode: local-docker

variables:
  redisHost: redis
  redisPort: 6379
  redisDbAccessKeys: 0
  redisDbResponseKeys: 1
  redisDbAccessKeyHash: 2
  redisDbRevokedDevices: 3
  redisDbHsmKeys: 4

  postgresHost: postgres
  postgresPort: 5432
  postgresUser: postgres
  postgresPassword: postgres
  postgresDbAuth: better_auth_auth
  postgresDbHsm: better_auth_hsm

  hsmHost: hsm
  hsmPort: 11111
